name: "Workflow"
author: "Mayank"
description: "Creating a workflow for my GitHub"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:  # Fixed spelling (was 'imputs')
  email:
    description: "The computer's email address"
    required: true
    default: "${{ github.actor }}@localhost"
  name:  # Fixed indentation
    description: "The computer's name"
    required: true
    default: "${{ github.actor }}"
