name: "Workflow"
author: "Mayank"
description: "Creating a workflow for my github"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
imputs:
  email:
    description: The computer's email address
    required: true
    default: ${{ github.actor }}@localhost
   name:
    description: The computer' name
    required: true
    default: ${{ github.actor }}